### ISSUE TITLE
Fail to run the example

### ISSUE THREAD

**Issue by ehsanmok** [rust-playground/rpc2.0#1]
Hi Dean

Unfortunately, I couldn't run the example successfully with `rustc 1.28.0 (9634041f0 2018-07-30)` in Ubunut 14.04. The error is 

```
Error: Request(Error { kind: Io(Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }), url: Some("http://localhost:4000/rpc") })
```
The problem is caused in [here](https://github.com/rust-playground/rpc2.0/blob/master/rpc-lib/src/client.rs#L131).

I suspect the example is not complete because there's no server running so cannot bind to that address!? also where's the method "Project.Find" in example?

Thanks

**Comment by deankarn** [comment]
Hey @ehsanmok 

Yes you are correct the example is incomplete as I do not have a server running, my primary focus was to make the client compatible with the RPC 2.0 spec and a few that are slightly off spec; there are a bunch of good servers that already exist.

I'll seek a good server out and add to the example :)
